# SPDX-FileCopyrightText: 2022 Radostin Stoyanov
#
# SPDX-License-Identifier: Apache-2.0

name: "Test P4 Examples"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-licenses:
    runs-on: ubuntu-latest
    name: Validate that all files have copyright and license info
    steps:
      - uses: actions/checkout@v6
      - name: Install REUSE
        run: |
          ./CI/install-uv.sh
      - name: Validate presence of copyright and license info (python w/reuse)
        run: |
          uvx reuse lint
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add .github/scripts to PATH
      run: echo "$GITHUB_WORKSPACE/.github/scripts" >> $GITHUB_PATH
    - name: Print p4test version
      run: p4test --version
    - name: Run runp4test.sh
      working-directory: ./examples
      run: bash runp4test.sh
